apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-aware-scheduling
  namespace: kube-system
  labels:
    app: tas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tas
  template:
    metadata:
      labels:
        app: tas
    spec:
      serviceAccountName: telemetry-aware-scheduling-service-account
      containers:
      - name: tas-scheduler
        image: gcr.io/google_containers/hyperkube:v1.16.3
        imagePullPolicy: IfNotPresent
        args:
        - kube-scheduler
        - --config=/tas-scheduler/config.yaml
        - -v=4
        volumeMounts:
        - name: tas-scheduler-config
          mountPath: /tas-scheduler
      - name: tascont
        command:
        - /controller
        - --syncPeriod=2s
        image: tas-controller 
        imagePullPolicy: IfNotPresent
      - name: tasext
        command:
        - /extender
        - --cacheEndpoint=http://127.0.0.1:8111/cache/
        - --cert=/tas/cert/tls.crt
        - --key=/tas/cert/tls.key
        image: tas-extender
        imagePullPolicy: IfNotPresent 
        volumeMounts:
        - name: certs
          mountPath: /tas/cert
      volumes:
      - name: certs
        secret:
          secretName: extender-secret
      - name: tas-scheduler-config
        configMap:
          name: scheduler-extender-config
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
